### ISSUE TITLE
Implement XSS scanner

### ISSUE THREAD

**Issue by igkostyuk** [ITA-Dnipro/Dp-230-Golang-Retraining#15]
[Implement XSS scanner](https://github.com/ITA-Dnipro/Dp-230-Test-XSS/tree/15-implement-xss-scanner)

**TODO:**
 - [x] Move some [dalfox](https://github.com/hahwul/dalfox/) functionality to package
- [x] Refactor scan function 
- [x] Validate payloads
- [x] add DOM Based XSS
